services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FRIDAYTOKEN=${FRIDAYTOKEN}
      - CLIENTID=${CLIENTID}
      - FRIDAYPORT=${FRIDAYPORT}
      - COSTAAPI=${COSTAAPI}
    ports:
      - '${FRIDAYPORT}:3000'
    volumes:
      - .:/app
    restart: unless-stopped
